# Package connectors
from ingestion.connectors.economic_indicators import EconomicIndicatorConnector
from ingestion.connectors.diario_oficial import DiarioOficialConnector
from ingestion.connectors.congreso import CongresoConnector
